//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedGun.AsyncApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedGun.AsyncApi.Properties.SRResource", typeof(SRResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be an active scope for name &apos;{0}&apos; to be written..
        /// </summary>
        internal static string ActiveScopeNeededForPropertyNameWriting {
            get {
                return ResourceManager.GetString("ActiveScopeNeededForPropertyNameWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is null, empty or consists only of white-space..
        /// </summary>
        internal static string ArgumentNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filed name &apos;{0}&apos; of extension doesn&apos;t begin with x-..
        /// </summary>
        internal static string ExtensionFieldNameMustBeginWithXDash {
            get {
                return ResourceManager.GetString("ExtensionFieldNameMustBeginWithXDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation level cannot be lower than 0..
        /// </summary>
        internal static string IndentationLevelInvalid {
            get {
                return ResourceManager.GetString("IndentationLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input item should be in type of &apos;{0}&apos;..
        /// </summary>
        internal static string InputItemShouldBeType {
            get {
                return ResourceManager.GetString("InputItemShouldBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference identifier &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidReferenceId {
            get {
                return ResourceManager.GetString("InvalidReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference Type..
        /// </summary>
        internal static string InvalidReferenceType {
            get {
                return ResourceManager.GetString("InvalidReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local reference must have type specified..
        /// </summary>
        internal static string LocalReferenceRequiresType {
            get {
                return ResourceManager.GetString("LocalReferenceRequiresType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active scope must be an object scope for property name &apos;{0}&apos; to be written..
        /// </summary>
        internal static string ObjectScopeNeededForPropertyNameWriting {
            get {
                return ResourceManager.GetString("ObjectScopeNeededForPropertyNameWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the Async API document..
        /// </summary>
        internal static string AsyncApiExceptionGenericError {
            get {
                return ResourceManager.GetString("AsyncApiExceptionGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given AsyncAPI format &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string AsyncApiFormatNotSupported {
            get {
                return ResourceManager.GetString("AsyncApiFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object element name &apos;{0}&apos; is required..
        /// </summary>
        internal static string AsyncApiObjectElementIsRequired {
            get {
                return ResourceManager.GetString("AsyncApiObjectElementIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AsyncApi element &apos;{0}&apos; is already marked as reference object..
        /// </summary>
        internal static string AsyncApiObjectMarkAsReference {
            get {
                return ResourceManager.GetString("AsyncApiObjectMarkAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the parameter location is &quot;path&quot;, this property is REQUIRED and its value MUST be true.
        /// </summary>
        internal static string AsyncApiParameterRequiredPropertyMandatory {
            get {
                return ResourceManager.GetString("AsyncApiParameterRequiredPropertyMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given AsyncAPI specification version &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string AsyncApiSpecVersionNotSupported {
            get {
                return ResourceManager.GetString("AsyncApiSpecVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported in Async API document..
        /// </summary>
        internal static string AsyncApiUnsupportedValueType {
            get {
                return ResourceManager.GetString("AsyncApiUnsupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing the Async API document..
        /// </summary>
        internal static string AsyncApiWriterExceptionGenericError {
            get {
                return ResourceManager.GetString("AsyncApiWriterExceptionGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given primitive type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string PrimitiveTypeNotSupported {
            get {
                return ResourceManager.GetString("PrimitiveTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference string &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string ReferenceHasInvalidFormat {
            get {
                return ResourceManager.GetString("ReferenceHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote reference not supported..
        /// </summary>
        internal static string RemoteReferenceNotSupported {
            get {
                return ResourceManager.GetString("RemoteReferenceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runtime expression &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string RuntimeExpressionHasInvalidFormat {
            get {
                return ResourceManager.GetString("RuntimeExpressionHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runtime expression &apos;{0}&apos; should start with &apos;$&apos;.
        /// </summary>
        internal static string RuntimeExpressionMustBeginWithDollar {
            get {
                return ResourceManager.GetString("RuntimeExpressionMustBeginWithDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope must be present to end..
        /// </summary>
        internal static string ScopeMustBePresentToEnd {
            get {
                return ResourceManager.GetString("ScopeMustBePresentToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope to end is expected to be of type &apos;{0}&apos; but it is of type &apos;{0}&apos;..
        /// </summary>
        internal static string ScopeToEndHasIncorrectType {
            get {
                return ResourceManager.GetString("ScopeToEndHasIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source expression &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string SourceExpressionHasInvalidFormat {
            get {
                return ResourceManager.GetString("SourceExpressionHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find visitor type registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownVisitorType {
            get {
                return ResourceManager.GetString("UnknownVisitorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; in &apos;{1}&apos; of components MUST match the regular expression &apos;{2}&apos;..
        /// </summary>
        internal static string Validation_ComponentsKeyMustMatchRegularExpr {
            get {
                return ResourceManager.GetString("Validation_ComponentsKeyMustMatchRegularExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension name &apos;{0}&apos; in &apos;{1}&apos; object MUST begin with &apos;x-&apos;..
        /// </summary>
        internal static string Validation_ExtensionNameMustBeginWithXDash {
            get {
                return ResourceManager.GetString("Validation_ExtensionNameMustBeginWithXDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; in &apos;{1}&apos; object is REQUIRED..
        /// </summary>
        internal static string Validation_FieldIsRequired {
            get {
                return ResourceManager.GetString("Validation_FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path item name &apos;{0}&apos; MUST begin with a slash..
        /// </summary>
        internal static string Validation_PathItemMustBeginWithSlash {
            get {
                return ResourceManager.GetString("Validation_PathItemMustBeginWithSlash", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to The same rule cannot be in the same rule set twice..
        /// </summary>
        internal static string Validation_RuleAddTwice {
            get {
                return ResourceManager.GetString("Validation_RuleAddTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema {0} must contain property specified in the discriminator {1} in the required field list..
        /// </summary>
        internal static string Validation_SchemaRequiredFieldListMustContainThePropertySpecifiedInTheDiscriminator {
            get {
                return ResourceManager.GetString("Validation_SchemaRequiredFieldListMustContainThePropertySpecifiedInTheDiscriminat" +
                        "or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; MUST be in the format of an email address..
        /// </summary>
        internal static string Validation_StringMustBeEmailAddress {
            get {
                return ResourceManager.GetString("Validation_StringMustBeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsyncAPI document must be added to an AsyncApiWorkspace to be able to resolve external references..
        /// </summary>
        internal static string WorkspaceRequiredForExternalReferenceResolution {
            get {
                return ResourceManager.GetString("WorkspaceRequiredForExternalReferenceResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path item name &apos;{0}&apos; MUST begin with a slash..
        /// </summary>
        internal static string Validation_ServerNameMustMatchPattern {
            get {
                return ResourceManager.GetString("Validation_ServerNameMustMatchPattern", resourceCulture);
            }
        }
    }
}
